### ISSUE TITLE
issue about laion5b-h-14 index, text query not related to response image results

### ISSUE THREAD

**Issue by marson666** [rom1504/clip-retrieval#288] opened 2023-06-25 13:58 UTC
Hi bro, thanks for you great work about this repo!
I build laion5B_h14_back successful locally, when i use clip_client search
`client = ClipClient(
url="http://127.0.0.1:1234/knn-service",
indice_name="laion5B-H-14",
aesthetic_score="",
aesthetic_weight=0.5,
modality=Modality.IMAGE,
num_images=100,
)

cat_results = client.query(text="a man is running")
`
the cat results seems very unrelated with the query "running", how to debug this problem?

`
cat_results[0]
{'caption': 'Jaké jsou vaše polibky podle znamení zvěrokruhu?', 'url': 'https://mujhoroskop.com/uploads/large_maxresdefault__4_1.jpg', 'id': 3139204416, 'similarity': 0.4006364643573761}

{'caption': 'Bouquet mariee bleu et blanc', 'url': 'https://cdn0.mariages.net/emp/fotos/4/7/1/4/bouquet-mariee-bleu-roi-blanc-fb_3_164714-161503496212461.jpg', 'id': 2441974434, 'similarity': 0.398070752620697}

{'caption': 'Monachus Hotels & Spa****', 'url': 'https://uk.zooverresources.com/images/PH136553L1W125H94RT2/Monachus-Hotels-and-Spa.jpg', 'id': 2487402917, 'similarity': 0.39280033111572266}
`

**Comment by adtygan** [comment] 2023-06-27 07:14
I face the same issue.

**Comment by rom1504** [comment] 2023-06-27 08:12
If you can provide information on what you did exactly it might help

**Comment by marson666** [comment] 2023-06-28 03:26
Hi bro, i follow the doc [https://github.com/rom1504/clip-retrieval/blob/main/docs/laion5B_h14_back.md](url) to build the laion5b-h-14 back service,  i download the index files and metadata files by aria2c command, the downloaded file name becomes their sha256sum not xxx.parquet, does the file name will affect the merge results? 

For example, i download the index file https://huggingface.co/datasets/laion/laion5b-h14-index/blob/main/index-parts/00.index, the file name on my disk is its sha256sum: 08a98d1b22f4d0841ad6cca402c2bae4e18858f26bf08c3d5eef72ff33456c6f  not 00.index, will this affect the results? 

The same as metadata file, i download the index file https://huggingface.co/datasets/laion/laion2b-multi-vit-h-14-embeddings/resolve/main/metadata/metadata_0000.parquet, the file name on my disk is its sha256sum: abbd777349c88901d35bdfdefa189e7625cfd3999072ad0da259738d097519cb  not metadata_0000.parquet, will this affect the results?

**Comment by rom1504** [comment] 2023-06-28 05:49
Yes it will. The original file names should be kept

**Comment by rom1504** [comment] 2023-06-28 06:13
If the instructions in the guide are producing this behavior we definitely
need to fix them

**Comment by adtygan** [comment] 2023-06-28 06:40
> Hi bro, i follow the doc [https://github.com/rom1504/clip-retrieval/blob/main/docs/laion5B_h14_back.md](url) to build the laion5b-h-14 back service,  i download the index files and metadata files by aria2c command, the downloaded file name becomes their sha256sum not xxx.parquet, does the file name will affect the merge results? 
> 
> For example, i download the index file https://huggingface.co/datasets/laion/laion5b-h14-index/blob/main/index-parts/00.index, the file name on my disk is its sha256sum: 08a98d1b22f4d0841ad6cca402c2bae4e18858f26bf08c3d5eef72ff33456c6f  not 00.index, will this affect the results? 
> 
> The same as metadata file, i download the index file https://huggingface.co/datasets/laion/laion2b-multi-vit-h-14-embeddings/resolve/main/metadata/metadata_0000.parquet, the file name on my disk is its sha256sum: abbd777349c88901d35bdfdefa189e7625cfd3999072ad0da259738d097519cb  not metadata_0000.parquet, will this affect the results? 

I faced this exact problem. So I renamed all the files to `<sha_sum>.parquet`.

**Comment by marson666** [comment] 2023-06-28 06:45
@rom1504 the command `for i in {0000..2268}; do aria2c -x 16 https://huggingface.co/datasets/laion/laion2b-multi-vit-h-14-embeddings/resolve/main/metadata/metadata_$i.parquet; done` in doc [https://github.com/rom1504/clip-retrieval/blob/main/docs/laion5B_h14_back.md](url) will generate sha256sum filename not the origin file name metadata_xxxx.parquet, maybe we should fix the output name to fix the problem?  

Another question, is there any quick methods to rename the filenames i have downloaded?

**Comment by adtygan** [comment] 2023-06-28 11:55
`for i in {0000..2268}; do aria2c -x 16 https://huggingface.co/datasets/laion/laion2b-multi-vit-h-14-embeddings/resolve/main/metadata/metadata_$i.parquet -o $i.parquet; done`. I think this should fix that problem. I just tested this on a one file and it downloads it in the correct format. Still haven't re-downloaded all the files to see if the problem is fixed.

**Comment by FlimFlamm** [comment] 2023-08-13 03:29
> Did you build the index and did the metadata merging in the right order ?
> 
> Very often this kind of problem is caused by metadata not being in the right order

Is it possible to use only the english metadata files and disinclude the muti and nolang ones? I'm getting the issue you describe I think because I only have the `metadata/0_en.arrow`  file. The issue is that my SSD is only 2 terabytes, so I was hoping to fit H14 this way, but I'm not sure what needs to be done to make it work.

**Comment by rom1504** [comment] 2023-08-13 10:29
Answered in your other issue

**Comment by rom1504** [comment] 2024-01-13 16:33
this seems fixed now, please open a focused issue on any problem if needed

**Closed by rom1504** 2024-01-13 16:33 UTC
